class Abezethibou extends Hostile {
  static Animation = null;

  constructor(text) {
    super(
      text,
      Abezethibou.Animation,
      createVector(-70, -10),
      createVector(width, height / 2)
    );
  }
  static loadAnimationFiles() {
    Abezethibou.Animation = loadAnimation(...Abezethibou.Sprites);
  }
  static Sprites = [
    "./assets/sprites/abezethibou/abezethibou (1).png",
    "./assets/sprites/abezethibou/abezethibou (2).png",
    "./assets/sprites/abezethibou/abezethibou (3).png",
    "./assets/sprites/abezethibou/abezethibou (4).png",
    "./assets/sprites/abezethibou/abezethibou (5).png",
    "./assets/sprites/abezethibou/abezethibou (6).png",
    "./assets/sprites/abezethibou/abezethibou (7).png",
    "./assets/sprites/abezethibou/abezethibou (8).png",
    "./assets/sprites/abezethibou/abezethibou (9).png",
    "./assets/sprites/abezethibou/abezethibou (10).png",
    "./assets/sprites/abezethibou/abezethibou (11).png",
    "./assets/sprites/abezethibou/abezethibou (12).png",
    "./assets/sprites/abezethibou/abezethibou (13).png",
    "./assets/sprites/abezethibou/abezethibou (14).png",
    "./assets/sprites/abezethibou/abezethibou (15).png",
    "./assets/sprites/abezethibou/abezethibou (16).png",
    "./assets/sprites/abezethibou/abezethibou (17).png",
    "./assets/sprites/abezethibou/abezethibou (18).png",
    "./assets/sprites/abezethibou/abezethibou (19).png",
    "./assets/sprites/abezethibou/abezethibou (20).png",
    "./assets/sprites/abezethibou/abezethibou (21).png",
    "./assets/sprites/abezethibou/abezethibou (22).png",
    "./assets/sprites/abezethibou/abezethibou (23).png",
    "./assets/sprites/abezethibou/abezethibou (24).png",
    "./assets/sprites/abezethibou/abezethibou (25).png",
    "./assets/sprites/abezethibou/abezethibou (26).png",
    "./assets/sprites/abezethibou/abezethibou (27).png",
    "./assets/sprites/abezethibou/abezethibou (28).png",
    "./assets/sprites/abezethibou/abezethibou (29).png",
    "./assets/sprites/abezethibou/abezethibou (30).png",
    "./assets/sprites/abezethibou/abezethibou (31).png",
    "./assets/sprites/abezethibou/abezethibou (32).png",
    "./assets/sprites/abezethibou/abezethibou (33).png",
    "./assets/sprites/abezethibou/abezethibou (34).png",
    "./assets/sprites/abezethibou/abezethibou (35).png",
    "./assets/sprites/abezethibou/abezethibou (36).png",
    "./assets/sprites/abezethibou/abezethibou (37).png",
    "./assets/sprites/abezethibou/abezethibou (38).png",
    "./assets/sprites/abezethibou/abezethibou (39).png",
    "./assets/sprites/abezethibou/abezethibou (40).png",
    "./assets/sprites/abezethibou/abezethibou (41).png",
    "./assets/sprites/abezethibou/abezethibou (42).png",
    "./assets/sprites/abezethibou/abezethibou (43).png",
    "./assets/sprites/abezethibou/abezethibou (44).png",
    "./assets/sprites/abezethibou/abezethibou (45).png",
    "./assets/sprites/abezethibou/abezethibou (46).png",
    "./assets/sprites/abezethibou/abezethibou (47).png",
    "./assets/sprites/abezethibou/abezethibou (48).png",
    "./assets/sprites/abezethibou/abezethibou (49).png",
    "./assets/sprites/abezethibou/abezethibou (50).png",
    "./assets/sprites/abezethibou/abezethibou (51).png",
    "./assets/sprites/abezethibou/abezethibou (52).png",
    "./assets/sprites/abezethibou/abezethibou (53).png",
    "./assets/sprites/abezethibou/abezethibou (54).png",
    "./assets/sprites/abezethibou/abezethibou (55).png",
    "./assets/sprites/abezethibou/abezethibou (56).png",
    "./assets/sprites/abezethibou/abezethibou (57).png",
    "./assets/sprites/abezethibou/abezethibou (58).png",
    "./assets/sprites/abezethibou/abezethibou (59).png",
    "./assets/sprites/abezethibou/abezethibou (60).png",
    "./assets/sprites/abezethibou/abezethibou (61).png",
    "./assets/sprites/abezethibou/abezethibou (62).png",
    "./assets/sprites/abezethibou/abezethibou (63).png",
    "./assets/sprites/abezethibou/abezethibou (64).png",
    "./assets/sprites/abezethibou/abezethibou (65).png",
    "./assets/sprites/abezethibou/abezethibou (66).png",
    "./assets/sprites/abezethibou/abezethibou (67).png",
    "./assets/sprites/abezethibou/abezethibou (68).png",
    "./assets/sprites/abezethibou/abezethibou (69).png",
    "./assets/sprites/abezethibou/abezethibou (70).png",
    "./assets/sprites/abezethibou/abezethibou (71).png",
    "./assets/sprites/abezethibou/abezethibou (72).png",
    "./assets/sprites/abezethibou/abezethibou (73).png",
    "./assets/sprites/abezethibou/abezethibou (74).png",
    "./assets/sprites/abezethibou/abezethibou (75).png",
  ];
}
