class Inker extends Hostile {
  static Animation = null;

  constructor(text) {
    super(text, Inker.Animation, createVector(-25, 7));
  }
  static loadAnimationFiles() {
    Inker.Animation = loadAnimation(...Inker.Sprites);
  }

  static Sprites = [
    "./assets/sprites/inker/inker (1).png",
    "./assets/sprites/inker/inker (2).png",
    "./assets/sprites/inker/inker (3).png",
    "./assets/sprites/inker/inker (4).png",
    "./assets/sprites/inker/inker (5).png",
    "./assets/sprites/inker/inker (6).png",
    "./assets/sprites/inker/inker (7).png",
    "./assets/sprites/inker/inker (8).png",
    "./assets/sprites/inker/inker (9).png",
    "./assets/sprites/inker/inker (10).png",
    "./assets/sprites/inker/inker (11).png",
    "./assets/sprites/inker/inker (12).png",
    "./assets/sprites/inker/inker (13).png",
    "./assets/sprites/inker/inker (14).png",
    "./assets/sprites/inker/inker (15).png",
    "./assets/sprites/inker/inker (16).png",
    "./assets/sprites/inker/inker (17).png",
    "./assets/sprites/inker/inker (18).png",
    "./assets/sprites/inker/inker (19).png",
    "./assets/sprites/inker/inker (20).png",
    "./assets/sprites/inker/inker (21).png",
    "./assets/sprites/inker/inker (22).png",
    "./assets/sprites/inker/inker (23).png",
    "./assets/sprites/inker/inker (24).png",
    "./assets/sprites/inker/inker (25).png",
    "./assets/sprites/inker/inker (26).png",
    "./assets/sprites/inker/inker (27).png",
    "./assets/sprites/inker/inker (28).png",
    "./assets/sprites/inker/inker (29).png",
    "./assets/sprites/inker/inker (30).png",
    "./assets/sprites/inker/inker (31).png",
    "./assets/sprites/inker/inker (32).png",
    "./assets/sprites/inker/inker (33).png",
    "./assets/sprites/inker/inker (34).png",
    "./assets/sprites/inker/inker (35).png",
    "./assets/sprites/inker/inker (36).png",
    "./assets/sprites/inker/inker (37).png",
    "./assets/sprites/inker/inker (38).png",
    "./assets/sprites/inker/inker (39).png",
    "./assets/sprites/inker/inker (40).png",
    "./assets/sprites/inker/inker (41).png",
    "./assets/sprites/inker/inker (42).png",
    "./assets/sprites/inker/inker (43).png",
    "./assets/sprites/inker/inker (44).png",
    "./assets/sprites/inker/inker (45).png",
    "./assets/sprites/inker/inker (46).png",
    "./assets/sprites/inker/inker (47).png",
    "./assets/sprites/inker/inker (48).png",
    "./assets/sprites/inker/inker (49).png",
    "./assets/sprites/inker/inker (50).png",
    "./assets/sprites/inker/inker (51).png",
    "./assets/sprites/inker/inker (52).png",
    "./assets/sprites/inker/inker (53).png",
    "./assets/sprites/inker/inker (54).png",
    "./assets/sprites/inker/inker (55).png",
    "./assets/sprites/inker/inker (56).png",
    "./assets/sprites/inker/inker (57).png",
    "./assets/sprites/inker/inker (58).png",
    "./assets/sprites/inker/inker (59).png",
    "./assets/sprites/inker/inker (60).png",
    "./assets/sprites/inker/inker (61).png",
    "./assets/sprites/inker/inker (62).png",
    "./assets/sprites/inker/inker (63).png",
    "./assets/sprites/inker/inker (64).png",
    "./assets/sprites/inker/inker (65).png",
    "./assets/sprites/inker/inker (66).png",
    "./assets/sprites/inker/inker (67).png",
    "./assets/sprites/inker/inker (68).png",
    "./assets/sprites/inker/inker (69).png",
    "./assets/sprites/inker/inker (70).png",
    "./assets/sprites/inker/inker (71).png",
    "./assets/sprites/inker/inker (72).png",
    "./assets/sprites/inker/inker (73).png",
    "./assets/sprites/inker/inker (74).png",
    "./assets/sprites/inker/inker (75).png",
    "./assets/sprites/inker/inker (76).png",
    "./assets/sprites/inker/inker (77).png",
    "./assets/sprites/inker/inker (78).png",
    "./assets/sprites/inker/inker (79).png",
    "./assets/sprites/inker/inker (80).png",
    "./assets/sprites/inker/inker (81).png",
    "./assets/sprites/inker/inker (82).png",
    "./assets/sprites/inker/inker (83).png",
    "./assets/sprites/inker/inker (84).png",
    "./assets/sprites/inker/inker (85).png",
    "./assets/sprites/inker/inker (86).png",
    "./assets/sprites/inker/inker (87).png",
    "./assets/sprites/inker/inker (88).png",
    "./assets/sprites/inker/inker (89).png",
    "./assets/sprites/inker/inker (90).png",
    "./assets/sprites/inker/inker (91).png",
  ];
}
