class Leona extends Hostile {
  static Animation = null;

  constructor(text) {
    super(text, Leona.Animation, createVector(-50, 15));
  }
  static loadAnimationFiles() {
    Leona.Animation = loadAnimation(...Leona.Sprites);
  }

  static Sprites = [
    "./assets/sprites/leona/leona (1).png",
    "./assets/sprites/leona/leona (2).png",
    "./assets/sprites/leona/leona (3).png",
    "./assets/sprites/leona/leona (4).png",
    "./assets/sprites/leona/leona (5).png",
    "./assets/sprites/leona/leona (6).png",
    "./assets/sprites/leona/leona (7).png",
    "./assets/sprites/leona/leona (8).png",
    "./assets/sprites/leona/leona (9).png",
    "./assets/sprites/leona/leona (10).png",
    "./assets/sprites/leona/leona (11).png",
    "./assets/sprites/leona/leona (12).png",
    "./assets/sprites/leona/leona (13).png",
    "./assets/sprites/leona/leona (14).png",
    "./assets/sprites/leona/leona (15).png",
    "./assets/sprites/leona/leona (16).png",
    "./assets/sprites/leona/leona (17).png",
    "./assets/sprites/leona/leona (18).png",
    "./assets/sprites/leona/leona (19).png",
    "./assets/sprites/leona/leona (20).png",
    "./assets/sprites/leona/leona (21).png",
    "./assets/sprites/leona/leona (22).png",
    "./assets/sprites/leona/leona (23).png",
    "./assets/sprites/leona/leona (24).png",
    "./assets/sprites/leona/leona (25).png",
    "./assets/sprites/leona/leona (26).png",
    "./assets/sprites/leona/leona (27).png",
    "./assets/sprites/leona/leona (28).png",
    "./assets/sprites/leona/leona (29).png",
    "./assets/sprites/leona/leona (30).png",
    "./assets/sprites/leona/leona (31).png",
    "./assets/sprites/leona/leona (32).png",
    "./assets/sprites/leona/leona (33).png",
    "./assets/sprites/leona/leona (34).png",
    "./assets/sprites/leona/leona (35).png",
    "./assets/sprites/leona/leona (36).png",
    "./assets/sprites/leona/leona (37).png",
    "./assets/sprites/leona/leona (38).png",
    "./assets/sprites/leona/leona (39).png",
    "./assets/sprites/leona/leona (40).png",
    "./assets/sprites/leona/leona (41).png",
    "./assets/sprites/leona/leona (42).png",
    "./assets/sprites/leona/leona (43).png",
    "./assets/sprites/leona/leona (44).png",
    "./assets/sprites/leona/leona (45).png",
    "./assets/sprites/leona/leona (46).png",
    "./assets/sprites/leona/leona (47).png",
    "./assets/sprites/leona/leona (48).png",
    "./assets/sprites/leona/leona (49).png",
    "./assets/sprites/leona/leona (50).png",
    "./assets/sprites/leona/leona (51).png",
    "./assets/sprites/leona/leona (52).png",
    "./assets/sprites/leona/leona (53).png",
    "./assets/sprites/leona/leona (54).png",
    "./assets/sprites/leona/leona (55).png",
    "./assets/sprites/leona/leona (56).png",
    "./assets/sprites/leona/leona (57).png",
    "./assets/sprites/leona/leona (58).png",
    "./assets/sprites/leona/leona (59).png",
    "./assets/sprites/leona/leona (60).png",
    "./assets/sprites/leona/leona (61).png",
  ];
}
