class Shellie extends Hostile {
  static Animation = null;

  constructor(text) {
    super(text, Shellie.Animation, createVector(12, 7));
  }
  static loadAnimationFiles() {
    Shellie.Animation = loadAnimation(...Shellie.Sprites);
  }

  static Sprites = [
    "./assets/sprites/shellie/shellie (1).png",
    "./assets/sprites/shellie/shellie (2).png",
    "./assets/sprites/shellie/shellie (3).png",
    "./assets/sprites/shellie/shellie (4).png",
    "./assets/sprites/shellie/shellie (5).png",
    "./assets/sprites/shellie/shellie (6).png",
    "./assets/sprites/shellie/shellie (7).png",
    "./assets/sprites/shellie/shellie (8).png",
    "./assets/sprites/shellie/shellie (9).png",
    "./assets/sprites/shellie/shellie (10).png",
    "./assets/sprites/shellie/shellie (11).png",
    "./assets/sprites/shellie/shellie (12).png",
    "./assets/sprites/shellie/shellie (13).png",
    "./assets/sprites/shellie/shellie (14).png",
    "./assets/sprites/shellie/shellie (15).png",
    "./assets/sprites/shellie/shellie (16).png",
    "./assets/sprites/shellie/shellie (17).png",
    "./assets/sprites/shellie/shellie (18).png",
    "./assets/sprites/shellie/shellie (19).png",
    "./assets/sprites/shellie/shellie (20).png",
    "./assets/sprites/shellie/shellie (21).png",
    "./assets/sprites/shellie/shellie (22).png",
    "./assets/sprites/shellie/shellie (23).png",
    "./assets/sprites/shellie/shellie (24).png",
    "./assets/sprites/shellie/shellie (25).png",
    "./assets/sprites/shellie/shellie (26).png",
    "./assets/sprites/shellie/shellie (27).png",
    "./assets/sprites/shellie/shellie (28).png",
    "./assets/sprites/shellie/shellie (29).png",
    "./assets/sprites/shellie/shellie (30).png",
    "./assets/sprites/shellie/shellie (31).png",
    "./assets/sprites/shellie/shellie (32).png",
    "./assets/sprites/shellie/shellie (33).png",
    "./assets/sprites/shellie/shellie (34).png",
    "./assets/sprites/shellie/shellie (35).png",
    "./assets/sprites/shellie/shellie (36).png",
    "./assets/sprites/shellie/shellie (37).png",
    "./assets/sprites/shellie/shellie (38).png",
    "./assets/sprites/shellie/shellie (39).png",
    "./assets/sprites/shellie/shellie (40).png",
    "./assets/sprites/shellie/shellie (41).png",
    "./assets/sprites/shellie/shellie (42).png",
    "./assets/sprites/shellie/shellie (43).png",
    "./assets/sprites/shellie/shellie (44).png",
    "./assets/sprites/shellie/shellie (45).png",
    "./assets/sprites/shellie/shellie (46).png",
    "./assets/sprites/shellie/shellie (47).png",
    "./assets/sprites/shellie/shellie (48).png",
    "./assets/sprites/shellie/shellie (49).png",
    "./assets/sprites/shellie/shellie (50).png",
    "./assets/sprites/shellie/shellie (51).png",
    "./assets/sprites/shellie/shellie (52).png",
    "./assets/sprites/shellie/shellie (53).png",
    "./assets/sprites/shellie/shellie (54).png",
    "./assets/sprites/shellie/shellie (55).png",
    "./assets/sprites/shellie/shellie (56).png",
    "./assets/sprites/shellie/shellie (57).png",
    "./assets/sprites/shellie/shellie (58).png",
    "./assets/sprites/shellie/shellie (59).png",
    "./assets/sprites/shellie/shellie (60).png",
  ];
}
