class Inky extends Neutral {
  static Animation = null;

  constructor(text) {
    super(text, Inky.Animation, createVector(0, -20));
  }
  static loadAnimationFiles() {
    Inky.Animation = loadAnimation(...Inky.Sprites);
  }

  static Sprites = [
    "./assets/sprites/inky/inky (1).png",
    "./assets/sprites/inky/inky (2).png",
    "./assets/sprites/inky/inky (3).png",
    "./assets/sprites/inky/inky (4).png",
    "./assets/sprites/inky/inky (5).png",
    "./assets/sprites/inky/inky (6).png",
    "./assets/sprites/inky/inky (7).png",
    "./assets/sprites/inky/inky (8).png",
    "./assets/sprites/inky/inky (9).png",
    "./assets/sprites/inky/inky (10).png",
    "./assets/sprites/inky/inky (11).png",
    "./assets/sprites/inky/inky (12).png",
    "./assets/sprites/inky/inky (13).png",
    "./assets/sprites/inky/inky (14).png",
    "./assets/sprites/inky/inky (15).png",
    "./assets/sprites/inky/inky (16).png",
    "./assets/sprites/inky/inky (17).png",
    "./assets/sprites/inky/inky (18).png",
    "./assets/sprites/inky/inky (19).png",
    "./assets/sprites/inky/inky (20).png",
    "./assets/sprites/inky/inky (21).png",
    "./assets/sprites/inky/inky (22).png",
    "./assets/sprites/inky/inky (23).png",
    "./assets/sprites/inky/inky (24).png",
    "./assets/sprites/inky/inky (25).png",
    "./assets/sprites/inky/inky (26).png",
    "./assets/sprites/inky/inky (27).png",
    "./assets/sprites/inky/inky (28).png",
    "./assets/sprites/inky/inky (29).png",
    "./assets/sprites/inky/inky (30).png",
    "./assets/sprites/inky/inky (31).png",
    "./assets/sprites/inky/inky (32).png",
    "./assets/sprites/inky/inky (33).png",
    "./assets/sprites/inky/inky (34).png",
    "./assets/sprites/inky/inky (35).png",
    "./assets/sprites/inky/inky (36).png",
    "./assets/sprites/inky/inky (37).png",
    "./assets/sprites/inky/inky (38).png",
    "./assets/sprites/inky/inky (39).png",
    "./assets/sprites/inky/inky (40).png",
    "./assets/sprites/inky/inky (41).png",
    "./assets/sprites/inky/inky (42).png",
    "./assets/sprites/inky/inky (43).png",
    "./assets/sprites/inky/inky (44).png",
    "./assets/sprites/inky/inky (45).png",
    "./assets/sprites/inky/inky (46).png",
    "./assets/sprites/inky/inky (47).png",
    "./assets/sprites/inky/inky (48).png",
    "./assets/sprites/inky/inky (49).png",
    "./assets/sprites/inky/inky (50).png",
    "./assets/sprites/inky/inky (51).png",
    "./assets/sprites/inky/inky (52).png",
    "./assets/sprites/inky/inky (53).png",
    "./assets/sprites/inky/inky (54).png",
    "./assets/sprites/inky/inky (55).png",
    "./assets/sprites/inky/inky (56).png",
    "./assets/sprites/inky/inky (57).png",
    "./assets/sprites/inky/inky (58).png",
    "./assets/sprites/inky/inky (59).png",
    "./assets/sprites/inky/inky (60).png",
    "./assets/sprites/inky/inky (61).png",
    "./assets/sprites/inky/inky (62).png",
    "./assets/sprites/inky/inky (63).png",
    "./assets/sprites/inky/inky (64).png",
    "./assets/sprites/inky/inky (65).png",
    "./assets/sprites/inky/inky (66).png",
    "./assets/sprites/inky/inky (67).png",
    "./assets/sprites/inky/inky (68).png",
    "./assets/sprites/inky/inky (69).png",
    "./assets/sprites/inky/inky (70).png",
    "./assets/sprites/inky/inky (71).png",
    "./assets/sprites/inky/inky (72).png",
    "./assets/sprites/inky/inky (73).png",
    "./assets/sprites/inky/inky (74).png",
    "./assets/sprites/inky/inky (75).png",
    "./assets/sprites/inky/inky (76).png",
    "./assets/sprites/inky/inky (77).png",
    "./assets/sprites/inky/inky (78).png",
    "./assets/sprites/inky/inky (79).png",
    "./assets/sprites/inky/inky (80).png",
    "./assets/sprites/inky/inky (81).png",
    "./assets/sprites/inky/inky (82).png",
    "./assets/sprites/inky/inky (83).png",
    "./assets/sprites/inky/inky (84).png",
    "./assets/sprites/inky/inky (85).png",
    "./assets/sprites/inky/inky (86).png",
    "./assets/sprites/inky/inky (87).png",
    "./assets/sprites/inky/inky (88).png",
    "./assets/sprites/inky/inky (89).png",
    "./assets/sprites/inky/inky (90).png",
    "./assets/sprites/inky/inky (91).png",
  ];
}
